# Generated by Django 4.2.5 on 2024-08-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
