# Generated by Django 4.2.5 on 2024-09-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_alter_expense_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
            preserve_default=False,
        ),
    ]
