# Generated by Django 4.2.5 on 2024-09-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expense_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectemployeeallocatedbudget',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
