# Generated by Django 4.2.5 on 2025-01-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_employee_avatar_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='upload',
            field=models.ImageField(default='uploads/default.png', upload_to='uploads/'),
        ),
    ]
