# Generated by Django 4.2.5 on 2025-01-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_expense_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(blank=True, choices=[('TRAVEL', 'Travel'), ('EVENTS', 'Events'), ('SUPPLIES', 'Supplies'), ('MEALS', 'Meals')], max_length=30, null=True),
        ),
    ]
