# Generated by Django 4.2.5 on 2025-02-26 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_expense_team_alter_employee_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
