# Generated by Django 4.2.20 on 2026-02-03 16:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_team_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='upload',
            field=models.FileField(default='uploads/default.png', upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='projectemployeeallocatedbudget',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1(Jan-Mar)'), ('Q2', 'Q2 (Apr-Jun'), ('Q3', 'Q3 (Jul-Sep'), ('Q4', 'Q4 (Oct-Dec)')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='FundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1(Jan-Mar)'), ('Q2', 'Q2 (Apr-Jun'), ('Q3', 'Q3 (Jul-Sep'), ('Q4', 'Q4 (Oct-Dec)')], max_length=2)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
