version: '2'
services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
        - LDAP_ORGANISATION=exampleorg
        - LDAP_DOMAIN=example.in
        - "LDAP_BASE_DN=dc=example,dc=in"
        - LDAP_ADMIN_PASSWORD=password
    ports:
        - 389:389
        - 636:636